// ═══════════════════════════════════════════════════════════════════════
// CompHub Template Data - 25 Boards, 228 Tasks, 6 Domains
// This file contains the master task taxonomy for compensation operations.
// Used by the server to seed the database on first run.
// ═══════════════════════════════════════════════════════════════════════

const DOMAIN_META = {
  "base-pay": { name: "Base Pay & Structures", color: "#3B82F6", icon: "dollar" },
  "variable-pay": { name: "Variable Pay & Incentives", color: "#10B981", icon: "target" },
  "exec-comp": { name: "Executive Compensation", color: "#8B5CF6", icon: "briefcase" },
  "global": { name: "Global / International", color: "#14B8A6", icon: "globe" },
  "compliance": { name: "Compliance & Governance", color: "#F59E0B", icon: "shield" },
  "operations": { name: "Operations & Administration", color: "#6366F1", icon: "settings" },
};

const BOARDS = [
  // ── DOMAIN: BASE PAY & STRUCTURES ──────────────────────────
  { id: "salary-structure", name: "Annual Salary Structure Review", domain: "base-pay", cadence: "Annual",
    desc: "End-to-end review and update of salary ranges, grades, and pay structures to maintain market competitiveness.",
    tasks: [
      { t: "Gather and validate market survey data for structure review", m: 7, o: "Analyst", p: "high" },
      { t: "Analyze current structure aging and market competitiveness", m: 8, o: "Sr Analyst", p: "high" },
      { t: "Model salary range adjustment scenarios (cost impact)", m: 8, o: "Sr Analyst", p: "critical" },
      { t: "Calculate total budget impact of proposed structure changes", m: 9, o: "Analyst", p: "high" },
      { t: "Prepare structure adjustment recommendation memo", m: 9, o: "Manager", p: "critical" },
      { t: "Present structure recommendation to leadership for approval", m: 9, o: "Director", p: "critical" },
      { t: "Implement approved salary structure changes in HRIS", m: 10, o: "Admin", p: "high" },
      { t: "Communicate updated salary ranges to HRBPs and hiring managers", m: 10, o: "Manager", p: "medium" },
    ]},
  { id: "market-pricing", name: "Market Pricing & Benchmarking", domain: "base-pay", cadence: "Annual",
    desc: "Annual cycle of survey participation, data collection, job matching, and competitive market analysis.",
    tasks: [
      { t: "Define annual survey participation strategy and budget", m: 1, o: "Manager", p: "high" },
      { t: "Complete compensation survey questionnaires and data submissions", m: 3, o: "Analyst", p: "high" },
      { t: "Receive and validate incoming survey results", m: 6, o: "Analyst", p: "high" },
      { t: "Age survey data to common effective date", m: 6, o: "Sr Analyst", p: "medium" },
      { t: "Blend multiple survey sources into composite market rates", m: 7, o: "Sr Analyst", p: "high" },
      { t: "Match internal jobs to benchmark survey positions", m: 7, o: "Analyst", p: "critical" },
      { t: "Calculate competitive market positioning by job family", m: 7, o: "Sr Analyst", p: "high" },
      { t: "Identify above-market and below-market outlier positions", m: 8, o: "Sr Analyst", p: "high" },
      { t: "Prepare comprehensive market pricing analysis report", m: 8, o: "Manager", p: "critical" },
      { t: "Present market pricing findings to compensation leadership", m: 8, o: "Director", p: "critical" },
    ]},
  { id: "merit-cycle", name: "Annual Merit Cycle", domain: "base-pay", cadence: "Annual",
    desc: "Full lifecycle management of the annual merit increase process from planning through post-cycle analysis.",
    tasks: [
      { t: "Review prior year merit cycle outcomes and lessons learned", m: 1, o: "Manager", p: "medium" },
      { t: "Develop merit philosophy and budget funding recommendation", m: 1, o: "Director", p: "critical" },
      { t: "Design merit increase matrix (performance x position in range)", m: 2, o: "Sr Analyst", p: "critical" },
      { t: "Build merit budget model with scenario analysis", m: 2, o: "Sr Analyst", p: "high" },
      { t: "Obtain merit budget approval from Finance and leadership", m: 2, o: "Director", p: "critical" },
      { t: "Configure compensation planning tool for merit cycle", m: 2, o: "Admin", p: "high" },
      { t: "Prepare and deliver manager training on merit guidelines", m: 3, o: "Manager", p: "high" },
      { t: "Launch merit planning cycle to managers", m: 3, o: "Manager", p: "critical" },
      { t: "Monitor manager submission progress and compliance", m: 3, o: "Analyst", p: "medium" },
      { t: "Review and calibrate manager merit recommendations", m: 4, o: "Manager", p: "critical" },
      { t: "Obtain final merit recommendations approval from leadership", m: 4, o: "Director", p: "critical" },
      { t: "Process approved merit increases in payroll/HRIS", m: 4, o: "Admin", p: "high" },
      { t: "Generate and distribute employee increase notification letters", m: 5, o: "Admin", p: "medium" },
      { t: "Conduct post-cycle analysis (distribution, budget variance, equity)", m: 5, o: "Sr Analyst", p: "high" },
    ]},
  { id: "pay-equity", name: "Pay Equity Analysis", domain: "base-pay", cadence: "Annual",
    desc: "Statistical analysis of compensation equity across protected classes with remediation planning.",
    tasks: [
      { t: "Define pay equity analysis scope, methodology, and timeline", m: 5, o: "Manager", p: "critical" },
      { t: "Extract and prepare employee compensation dataset", m: 5, o: "Analyst", p: "high" },
      { t: "Validate data quality, completeness, and coding accuracy", m: 6, o: "Analyst", p: "high" },
      { t: "Run multivariate regression analysis by job group", m: 6, o: "Sr Analyst", p: "critical" },
      { t: "Identify statistical outliers and potential pay gaps", m: 6, o: "Sr Analyst", p: "critical" },
      { t: "Investigate root causes of flagged pay disparities", m: 7, o: "Sr Analyst", p: "high" },
      { t: "Develop remediation adjustment recommendations", m: 7, o: "Manager", p: "critical" },
      { t: "Calculate total remediation cost and prepare budget request", m: 7, o: "Sr Analyst", p: "high" },
      { t: "Obtain approval and process pay equity adjustments", m: 8, o: "Director", p: "critical" },
      { t: "Document methodology, findings, and actions for legal/audit", m: 8, o: "Manager", p: "high" },
    ]},
  { id: "job-architecture", name: "Job Architecture & Evaluation", domain: "base-pay", cadence: "Annual",
    desc: "Maintenance and governance of job families, levels, descriptions, and FLSA classifications.",
    tasks: [
      { t: "Review and maintain job family/sub-family framework", m: 1, o: "Manager", p: "medium" },
      { t: "Evaluate new and revised positions using evaluation methodology", m: 1, o: "Sr Analyst", p: "high" },
      { t: "Maintain job description library and catalog", m: 2, o: "Analyst", p: "medium" },
      { t: "Conduct annual FLSA exemption status classification review", m: 3, o: "Sr Analyst", p: "critical" },
      { t: "Map evaluated positions to salary grades and bands", m: 3, o: "Sr Analyst", p: "high" },
      { t: "Review and update career progression pathways", m: 4, o: "Manager", p: "medium" },
      { t: "Audit job codes for consistency and data integrity", m: 4, o: "Analyst", p: "medium" },
      { t: "Produce annual job architecture health and coverage report", m: 5, o: "Manager", p: "medium" },
    ]},

  // ── DOMAIN: VARIABLE PAY & INCENTIVES ──────────────────────
  { id: "annual-incentive", name: "Annual Incentive Plan (AIP) Administration", domain: "variable-pay", cadence: "Annual",
    desc: "Design, execution, and analysis of the short-term annual incentive bonus program.",
    tasks: [
      { t: "Review prior year AIP design effectiveness and payout analysis", m: 1, o: "Sr Analyst", p: "high" },
      { t: "Benchmark incentive plan design against market practices", m: 1, o: "Analyst", p: "medium" },
      { t: "Develop annual incentive plan design recommendations", m: 2, o: "Manager", p: "critical" },
      { t: "Set corporate and business unit performance targets", m: 2, o: "Director", p: "critical" },
      { t: "Obtain AIP plan approval from leadership/board", m: 2, o: "Director", p: "critical" },
      { t: "Communicate approved plan details to eligible participants", m: 3, o: "Manager", p: "high" },
      { t: "Track and report interim performance against AIP targets (Q1)", m: 4, o: "Analyst", p: "medium" },
      { t: "Track and report interim performance against AIP targets (Q2)", m: 7, o: "Analyst", p: "medium" },
      { t: "Track and report interim performance against AIP targets (Q3)", m: 10, o: "Analyst", p: "medium" },
      { t: "Calculate preliminary bonus pool and individual payouts", m: 1, o: "Sr Analyst", p: "critical" },
      { t: "Conduct QA on payout calculations and present for approval", m: 1, o: "Manager", p: "critical" },
      { t: "Process bonus payments through payroll and prepare plan effectiveness report", m: 2, o: "Admin", p: "high" },
    ]},
  { id: "sales-comp", name: "Sales Compensation Management", domain: "variable-pay", cadence: "Annual",
    desc: "Design, administration, and monitoring of sales commission and incentive plans.",
    tasks: [
      { t: "Analyze prior year plan effectiveness and quota attainment distribution", m: 11, o: "Sr Analyst", p: "high" },
      { t: "Design or redesign sales compensation plan structure", m: 11, o: "Manager", p: "critical" },
      { t: "Model plan costs under multiple performance scenarios", m: 12, o: "Sr Analyst", p: "high" },
      { t: "Obtain sales leadership and finance approval on plan design", m: 12, o: "Director", p: "critical" },
      { t: "Configure sales performance management (SPM) tool", m: 1, o: "Admin", p: "high" },
      { t: "Conduct sales comp plan rollout communication and training", m: 1, o: "Manager", p: "high" },
      { t: "Process monthly/quarterly commission calculations", m: 3, o: "Analyst", p: "high" },
      { t: "Manage commission disputes and exception requests", m: 6, o: "Sr Analyst", p: "medium" },
      { t: "Monitor mid-year plan effectiveness and recommend adjustments", m: 7, o: "Manager", p: "high" },
      { t: "Conduct year-end sales comp plan audit and reconciliation", m: 12, o: "Sr Analyst", p: "high" },
    ]},
  { id: "lti-equity", name: "Long-Term Incentive / Equity Administration", domain: "variable-pay", cadence: "Annual",
    desc: "Administration of equity grants (RSUs, options, PSUs), vesting, exercises, and compliance.",
    tasks: [
      { t: "Develop annual equity grant strategy and per-level guidelines", m: 1, o: "Director", p: "critical" },
      { t: "Determine share pool size and run dilution analysis", m: 1, o: "Sr Analyst", p: "high" },
      { t: "Prepare individual equity grant recommendations by level/performance", m: 2, o: "Manager", p: "critical" },
      { t: "Obtain board/compensation committee grant approval", m: 3, o: "Director", p: "critical" },
      { t: "Process equity grants (RSUs, options, PSUs) in equity plan system", m: 3, o: "Admin", p: "high" },
      { t: "Manage ongoing vesting schedule administration and communications", m: 6, o: "Admin", p: "medium" },
      { t: "Process stock option exercises and RSU settlements", m: 6, o: "Admin", p: "medium" },
      { t: "Handle termination-related equity treatment and forfeiture processing", m: 6, o: "Sr Analyst", p: "high" },
      { t: "Monitor and enforce blackout period trading compliance", m: 3, o: "Legal", p: "high" },
      { t: "Track performance share unit metric progress (interim)", m: 7, o: "Sr Analyst", p: "medium" },
      { t: "Coordinate Section 16 insider transaction filings", m: 4, o: "Legal", p: "critical" },
      { t: "Prepare annual share utilization and dilution tracking report", m: 12, o: "Sr Analyst", p: "high" },
    ]},
  { id: "recognition", name: "Recognition & Spot Awards", domain: "variable-pay", cadence: "Annual",
    desc: "Design and administration of employee recognition programs and discretionary awards.",
    tasks: [
      { t: "Review and update recognition program design and criteria", m: 1, o: "Manager", p: "medium" },
      { t: "Set and allocate annual recognition budget by department", m: 1, o: "Manager", p: "medium" },
      { t: "Process spot bonus and recognition award nominations (ongoing)", m: 6, o: "Admin", p: "low" },
      { t: "Monitor quarterly program utilization and spending trends", m: 4, o: "Analyst", p: "low" },
      { t: "Analyze recognition program effectiveness and engagement impact", m: 10, o: "Sr Analyst", p: "medium" },
      { t: "Prepare annual recognition program summary report", m: 12, o: "Manager", p: "medium" },
    ]},
  { id: "retention", name: "Retention Program Management", domain: "variable-pay", cadence: "Annual",
    desc: "Identification of flight risks and design/execution of targeted retention strategies.",
    tasks: [
      { t: "Identify high flight-risk employees using predictive analytics", m: 3, o: "Sr Analyst", p: "high" },
      { t: "Design targeted retention bonus program framework", m: 4, o: "Manager", p: "high" },
      { t: "Model retention investment ROI scenarios and budget impact", m: 4, o: "Sr Analyst", p: "high" },
      { t: "Process retention bonus agreements and scheduled payments", m: 5, o: "Admin", p: "medium" },
      { t: "Track retention bonus clawback provisions and compliance", m: 9, o: "Admin", p: "medium" },
      { t: "Analyze retention program effectiveness and turnover outcomes", m: 11, o: "Sr Analyst", p: "high" },
    ]},

  // ── DOMAIN: EXECUTIVE COMPENSATION ─────────────────────────
  { id: "exec-annual", name: "Annual Executive Comp Cycle", domain: "exec-comp", cadence: "Annual",
    desc: "Annual executive compensation benchmarking, recommendation, and approval cycle.",
    tasks: [
      { t: "Conduct peer group validation and annual update", m: 8, o: "Sr Analyst", p: "critical" },
      { t: "Complete executive compensation benchmarking study", m: 9, o: "Sr Analyst", p: "critical" },
      { t: "Perform pay-for-performance alignment analysis", m: 9, o: "Sr Analyst", p: "high" },
      { t: "Prepare executive tally sheets (total compensation snapshots)", m: 10, o: "Analyst", p: "high" },
      { t: "Develop executive compensation change recommendations", m: 10, o: "Manager", p: "critical" },
      { t: "Prepare compensation committee presentation materials", m: 10, o: "Manager", p: "critical" },
      { t: "Support compensation committee meeting and deliberations", m: 11, o: "Director", p: "critical" },
      { t: "Process approved executive compensation changes", m: 12, o: "Admin", p: "high" },
      { t: "Review and update executive employment agreements", m: 12, o: "Legal", p: "high" },
      { t: "Generate executive total compensation statements", m: 1, o: "Sr Analyst", p: "medium" },
    ]},
  { id: "proxy-cda", name: "Proxy Statement & CD&A", domain: "exec-comp", cadence: "Annual",
    desc: "Preparation of proxy statement compensation disclosures including CD&A, pay tables, and say-on-pay.",
    tasks: [
      { t: "Draft Compensation Discussion and Analysis (CD&A) narrative", m: 1, o: "Manager", p: "critical" },
      { t: "Compile Summary Compensation Table and supporting data tables", m: 1, o: "Sr Analyst", p: "critical" },
      { t: "Prepare Pay vs Performance (PVP) disclosure table", m: 2, o: "Sr Analyst", p: "critical" },
      { t: "Calculate CEO Pay Ratio disclosure", m: 2, o: "Analyst", p: "high" },
      { t: "Review ISS and Glass Lewis policy updates and voting guidelines", m: 1, o: "Manager", p: "high" },
      { t: "Develop Say-on-Pay narrative and supporting materials", m: 2, o: "Manager", p: "critical" },
      { t: "Coordinate proxy draft review with legal counsel", m: 3, o: "Legal", p: "critical" },
      { t: "Support shareholder engagement on compensation matters", m: 3, o: "Director", p: "high" },
      { t: "File DEF 14A proxy materials with SEC", m: 4, o: "Legal", p: "critical" },
      { t: "Conduct post-Annual Meeting say-on-pay vote analysis", m: 6, o: "Sr Analyst", p: "medium" },
    ]},
  { id: "board-committee", name: "Compensation Committee Governance", domain: "exec-comp", cadence: "Annual",
    desc: "Compensation committee calendar, meeting preparation, governance compliance, and advisory support.",
    tasks: [
      { t: "Develop annual compensation committee meeting calendar and workplan", m: 12, o: "Manager", p: "high" },
      { t: "Prepare advance materials for each committee meeting (4x/year)", m: 1, o: "Manager", p: "critical" },
      { t: "Coordinate with committee chair on agenda priorities and sequencing", m: 1, o: "Director", p: "high" },
      { t: "Draft committee meeting minutes and document formal resolutions", m: 3, o: "Analyst", p: "medium" },
      { t: "Track and report on committee action item completion status", m: 6, o: "Analyst", p: "medium" },
      { t: "Prepare compensation committee annual effectiveness self-assessment", m: 11, o: "Manager", p: "medium" },
      { t: "Update committee charter and governance documentation", m: 12, o: "Legal", p: "medium" },
      { t: "Brief new committee members on compensation program landscape", m: 6, o: "Director", p: "high" },
    ]},
  { id: "director-comp", name: "Board of Directors Compensation", domain: "exec-comp", cadence: "Annual",
    desc: "Comprehensive director pay program design, benchmarking, equity administration, and regulatory disclosure.",
    tasks: [
      { t: "Review director compensation philosophy and market positioning strategy", m: 7, o: "Director", p: "high" },
      { t: "Benchmark director retainer, meeting fees, and equity against peer group", m: 8, o: "Sr Analyst", p: "critical" },
      { t: "Analyze director pay trends and emerging governance best practices", m: 8, o: "Sr Analyst", p: "high" },
      { t: "Model director compensation scenarios (cash vs. equity mix optimization)", m: 9, o: "Sr Analyst", p: "high" },
      { t: "Prepare director compensation program change recommendations", m: 9, o: "Manager", p: "critical" },
      { t: "Present director pay recommendations to governance/compensation committee", m: 10, o: "Director", p: "critical" },
      { t: "Process annual director equity grants (RSUs, stock options, DSUs)", m: 11, o: "Admin", p: "high" },
      { t: "Administer director deferred stock unit (DSU) elections and distributions", m: 1, o: "Sr Analyst", p: "medium" },
      { t: "Calculate and process director annual cash retainer and committee premiums", m: 1, o: "Admin", p: "high" },
      { t: "Monitor director stock ownership guideline compliance", m: 3, o: "Analyst", p: "high" },
      { t: "Prepare director compensation disclosure tables for proxy statement", m: 2, o: "Sr Analyst", p: "critical" },
      { t: "Onboard new director compensation package (retainer, equity, benefits)", m: 6, o: "Manager", p: "medium" },
      { t: "Review committee chair and lead independent director premium adequacy", m: 8, o: "Sr Analyst", p: "medium" },
      { t: "Prepare annual director total compensation summary statements", m: 12, o: "Analyst", p: "medium" },
    ]},
  { id: "exec-benefits", name: "Executive Benefits & Perquisites", domain: "exec-comp", cadence: "Annual",
    desc: "Administration of NQDC plans, SERPs, perquisites, and change-in-control provisions.",
    tasks: [
      { t: "Administer nonqualified deferred compensation plans (409A compliance)", m: 1, o: "Sr Analyst", p: "critical" },
      { t: "Manage supplemental executive retirement plan (SERP) calculations", m: 3, o: "Sr Analyst", p: "high" },
      { t: "Track and value executive perquisites for tax reporting", m: 12, o: "Analyst", p: "high" },
      { t: "Conduct change-in-control benefit modeling (Section 280G analysis)", m: 6, o: "Sr Analyst", p: "high" },
      { t: "Review executive severance plan provisions and triggers", m: 6, o: "Legal", p: "medium" },
      { t: "Monitor Section 162(m) performance-based pay deductibility", m: 9, o: "Sr Analyst", p: "high" },
      { t: "Coordinate executive financial planning and counseling program", m: 1, o: "Manager", p: "low" },
      { t: "Prepare annual executive benefits summary statements", m: 12, o: "Analyst", p: "medium" },
    ]},

  // ── DOMAIN: GLOBAL / INTERNATIONAL ─────────────────────────
  { id: "global-structures", name: "Global Pay Structure Management", domain: "global", cadence: "Annual",
    desc: "Country-specific salary structure review, currency analysis, and global grading harmonization.",
    tasks: [
      { t: "Review country-specific salary structure competitiveness", m: 7, o: "Sr Analyst", p: "high" },
      { t: "Analyze currency exchange rate impact on compensation costs", m: 7, o: "Analyst", p: "high" },
      { t: "Update cost of living adjustments (COLA) by country", m: 8, o: "Analyst", p: "medium" },
      { t: "Review and update geographic pay differentials", m: 8, o: "Sr Analyst", p: "high" },
      { t: "Harmonize global job grading framework across regions", m: 9, o: "Manager", p: "critical" },
      { t: "Monitor local statutory minimum wage changes by country", m: 1, o: "Analyst", p: "high" },
      { t: "Review social security and statutory benefit contribution rates", m: 3, o: "Analyst", p: "medium" },
      { t: "Prepare global compensation cost benchmarking report", m: 10, o: "Manager", p: "high" },
    ]},
  { id: "global-mobility", name: "Global Mobility & Expatriate Compensation", domain: "global", cadence: "Annual",
    desc: "International assignment policy, package design, tax equalization, and allowance benchmarking.",
    tasks: [
      { t: "Update global mobility and international assignment policy", m: 1, o: "Manager", p: "high" },
      { t: "Prepare assignment cost projections for new assignments", m: 2, o: "Sr Analyst", p: "high" },
      { t: "Design expatriate compensation packages (balance sheet approach)", m: 2, o: "Sr Analyst", p: "critical" },
      { t: "Calculate tax equalization estimates and year-end settlements", m: 3, o: "Analyst", p: "high" },
      { t: "Update COLA and hardship/danger pay allowances by location", m: 4, o: "Analyst", p: "medium" },
      { t: "Benchmark housing allowances by assignment location", m: 5, o: "Analyst", p: "medium" },
      { t: "Coordinate home/host country payroll split calculations", m: 6, o: "Admin", p: "high" },
      { t: "Process new international assignment setup in HRIS", m: 6, o: "Admin", p: "medium" },
      { t: "Manage repatriation compensation and benefit transitions", m: 9, o: "Sr Analyst", p: "medium" },
      { t: "Conduct annual assignment cost true-up reconciliation", m: 12, o: "Sr Analyst", p: "high" },
    ]},
  { id: "intl-compliance", name: "International Compliance", domain: "global", cadence: "Annual",
    desc: "Country labor law monitoring, works council coordination, data privacy, and statutory reporting.",
    tasks: [
      { t: "Monitor country-specific labor law and pay regulation changes", m: 1, o: "Legal", p: "high" },
      { t: "Review works council and collective bargaining agreement impacts", m: 3, o: "Legal", p: "medium" },
      { t: "Ensure data privacy compliance for compensation data (GDPR/local)", m: 4, o: "Legal", p: "critical" },
      { t: "Track international pay equity legislative requirements", m: 5, o: "Sr Analyst", p: "high" },
      { t: "Prepare statutory compensation reporting by country", m: 6, o: "Analyst", p: "high" },
      { t: "Coordinate with local tax advisors on filing requirements", m: 3, o: "Finance", p: "high" },
      { t: "Review cross-border transfer compensation tax implications", m: 6, o: "Finance", p: "medium" },
      { t: "Conduct annual international compliance risk assessment", m: 11, o: "Manager", p: "high" },
    ]},

  // ── DOMAIN: COMPLIANCE & GOVERNANCE ────────────────────────
  { id: "reg-compliance", name: "Regulatory Compliance", domain: "compliance", cadence: "Annual",
    desc: "FLSA, EEO-1, pay transparency, AAP, and government contractor compliance management.",
    tasks: [
      { t: "Conduct annual FLSA audit (exemption status classifications)", m: 3, o: "Sr Analyst", p: "critical" },
      { t: "Prepare EEO-1 Component 2 pay data submission", m: 5, o: "Analyst", p: "critical" },
      { t: "Review state and local pay transparency law compliance", m: 1, o: "Legal", p: "critical" },
      { t: "Update pay band and salary range postings per jurisdiction", m: 2, o: "Analyst", p: "high" },
      { t: "Support Affirmative Action Plan (AAP) compensation analysis", m: 4, o: "Sr Analyst", p: "high" },
      { t: "Review workers compensation classification codes", m: 6, o: "Admin", p: "medium" },
      { t: "Ensure government contractor FAR/DCAA cost compliance", m: 8, o: "Sr Analyst", p: "critical" },
      { t: "Support SOX control testing for compensation processes", m: 9, o: "Manager", p: "high" },
      { t: "Prepare for and support internal/external compensation audits", m: 10, o: "Manager", p: "high" },
      { t: "Monitor regulatory and legislative changes affecting compensation", m: 1, o: "Legal", p: "high" },
    ]},
  { id: "pay-transparency", name: "Pay Transparency & Reporting", domain: "compliance", cadence: "Annual",
    desc: "Pay range disclosure compliance, pay gap reporting, and internal equity communications.",
    tasks: [
      { t: "Inventory applicable pay transparency requirements by jurisdiction", m: 1, o: "Legal", p: "critical" },
      { t: "Develop and maintain pay range disclosure language and standards", m: 2, o: "Manager", p: "high" },
      { t: "Update job posting salary ranges for legal compliance", m: 2, o: "Analyst", p: "high" },
      { t: "Prepare manager talking points on pay range questions", m: 3, o: "Manager", p: "medium" },
      { t: "Audit active job postings for pay transparency compliance", m: 6, o: "Analyst", p: "high" },
      { t: "Prepare gender/ethnicity pay gap reporting (where mandated)", m: 5, o: "Sr Analyst", p: "critical" },
      { t: "Develop internal pay equity communication strategy", m: 4, o: "Manager", p: "medium" },
      { t: "Monitor emerging pay transparency legislation across jurisdictions", m: 9, o: "Legal", p: "medium" },
    ]},
  { id: "comp-governance", name: "Compensation Governance", domain: "compliance", cadence: "Annual",
    desc: "Compensation philosophy, policies, approval authorities, and risk management documentation.",
    tasks: [
      { t: "Review and update compensation philosophy statement", m: 1, o: "Director", p: "high" },
      { t: "Update salary administration and pay decision guidelines", m: 2, o: "Manager", p: "medium" },
      { t: "Review compensation approval authority matrix", m: 2, o: "Director", p: "medium" },
      { t: "Maintain compensation plan documents and amendments", m: 3, o: "Legal", p: "medium" },
      { t: "Track and report on compensation policy exceptions", m: 6, o: "Analyst", p: "medium" },
      { t: "Conduct annual compensation risk assessment", m: 8, o: "Manager", p: "high" },
      { t: "Update compensation controls and SOX documentation", m: 9, o: "Manager", p: "high" },
      { t: "Prepare governance summary report for leadership review", m: 10, o: "Director", p: "high" },
    ]},

  // ── DOMAIN: OPERATIONS & ADMINISTRATION ────────────────────
  { id: "survey-mgmt", name: "Survey Participation & Management", domain: "operations", cadence: "Annual",
    desc: "Management of compensation survey vendor relationships, submissions, and data library.",
    tasks: [
      { t: "Develop annual survey participation calendar and sourcing strategy", m: 12, o: "Manager", p: "high" },
      { t: "Submit compensation data to contracted surveys", m: 3, o: "Analyst", p: "high" },
      { t: "Validate and reconcile incoming survey results against prior year", m: 6, o: "Analyst", p: "high" },
      { t: "Maintain internal job-to-survey benchmark matching library", m: 7, o: "Analyst", p: "medium" },
      { t: "Evaluate new survey sources for potential participation", m: 8, o: "Manager", p: "low" },
      { t: "Manage survey vendor contracts and annual renewals", m: 10, o: "Manager", p: "medium" },
      { t: "Build and maintain survey data aging factors by industry", m: 7, o: "Sr Analyst", p: "medium" },
      { t: "Prepare annual survey participation and ROI summary report", m: 11, o: "Manager", p: "medium" },
    ]},
  { id: "hris-tech", name: "HRIS & Technology Management", domain: "operations", cadence: "Annual",
    desc: "Compensation system configuration, reporting, data quality, and technology roadmap.",
    tasks: [
      { t: "Configure compensation planning tool for annual cycle launch", m: 2, o: "Admin", p: "critical" },
      { t: "Develop and maintain compensation dashboards and standard reports", m: 1, o: "Analyst", p: "medium" },
      { t: "Conduct quarterly compensation data quality audits (Q1)", m: 4, o: "Analyst", p: "medium" },
      { t: "Manage user access and security roles for compensation systems", m: 1, o: "Admin", p: "high" },
      { t: "Maintain system integrations (HRIS to payroll to comp planning)", m: 5, o: "Admin", p: "high" },
      { t: "Evaluate new compensation technology tools and vendors", m: 8, o: "Manager", p: "low" },
      { t: "Document system configuration and process workflows", m: 9, o: "Admin", p: "medium" },
      { t: "Support compensation system upgrades and UAT testing", m: 10, o: "Admin", p: "high" },
    ]},
  { id: "budget-planning", name: "Budget & Financial Planning", domain: "operations", cadence: "Annual",
    desc: "Total compensation budgeting, forecasting, variance analysis, and financial audit support.",
    tasks: [
      { t: "Develop annual total compensation budget (all components)", m: 9, o: "Manager", p: "critical" },
      { t: "Support headcount planning with compensation cost models", m: 9, o: "Sr Analyst", p: "high" },
      { t: "Prepare quarterly compensation cost forecasts (Q1)", m: 4, o: "Analyst", p: "high" },
      { t: "Report budget variance with explanatory analysis", m: 7, o: "Analyst", p: "medium" },
      { t: "Calculate and communicate monthly compensation accruals", m: 1, o: "Finance", p: "high" },
      { t: "Support financial audit requests related to compensation", m: 3, o: "Manager", p: "high" },
      { t: "Model compensation cost impact of organizational changes", m: 6, o: "Sr Analyst", p: "high" },
      { t: "Prepare total rewards cost per employee analysis", m: 11, o: "Sr Analyst", p: "medium" },
    ]},
  { id: "team-stakeholder", name: "Team & Stakeholder Management", domain: "operations", cadence: "Annual",
    desc: "Team development, manager training, HRBP support, and stakeholder communication cadence.",
    tasks: [
      { t: "Develop annual compensation team development and training plan", m: 1, o: "Director", p: "medium" },
      { t: "Design and deliver manager compensation literacy training", m: 3, o: "Manager", p: "high" },
      { t: "Build and maintain HRBP compensation consulting playbook", m: 2, o: "Manager", p: "medium" },
      { t: "Develop annual compensation communication calendar", m: 1, o: "Manager", p: "medium" },
      { t: "Conduct stakeholder satisfaction survey and develop action plan", m: 6, o: "Manager", p: "medium" },
      { t: "Prepare quarterly compensation status report for HR leadership", m: 4, o: "Director", p: "high" },
    ]},
];

module.exports = { DOMAIN_META, BOARDS };
